# config/packages/knpu_oauth2_client.yaml
knpu_oauth2_client:
    clients:
        strava:
            type: strava
            client_id: '%env(OAUTH_STRAVA_CLIENT_ID)%'
            client_secret: '%env(OAUTH_STRAVA_CLIENT_SECRET)%'
            redirect_route: connect_strava_check
            redirect_params: { }
